Try include instead of require;
The require gives an error:

Error: Could not find dependency Class[Nagios::Nagios-351] ...

And  the online doc/forums do not help.  The following suggestion does
not work:

http://serverfault.com/questions/423273/how-to-break-dependency-cycle-in-puppet-when-including-classes